version: '3.8'

services:
  wechat-bot:
    build: .
    ports:
      - "4201:4201"
    env_file:
      - .env
    environment:
      - FLASK_ENV=production
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4201/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
